name: mahospital
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0 #963 firebase.google.com
  firebase_auth: ^4.3.0 #1563 firebase.google.com
  firebase_storage: ^11.0.14 #558 firebase.google.com
  cloud_firestore: ^4.4.5 #1446 firebase.google.com
  # cloud_firestore_web: ^2.4.1

  # google_ml_kit: ^0.13.0 #77 firebase.google.com
  google_mlkit_text_recognition: ^0.5.0
  # firebase_database: ^7.1.1 #262 firebase.google.com
  cloud_functions: ^4.0.11 #169 firebase.google.com
  image_picker: ^0.8.4 #2136 flutter.dev
  camera: ^0.10.3+2 #602 flutter.dev
  # camera_web: ^0.2.1+1 #17 flutter.dev
  # path_provider: ^2.0.1 #1631 flutter.dev
  provider: ^6.0.5 #4424 dash-overflow.net
  # path: ^1.8.0 #456 dart.dev
  encrypt: ^5.0.0 #244 unknown
  universal_html: ^2.0.8 #208 dint.dev
  # local_auth: ^1.1.7 #633 flutter.dev
  # sqflite: ^2.0.0+3 #1783 tekartik.com
  qr_flutter: ^4.0.0 #591 theyakka.com
  qr_code_scanner: ^1.0.1 #501 unknown
  screenshot: ^1.2.3 #361 dsi.dev
  # multi_image_picker2: ^5.0.2 #10 unknown
  # permission_handler: ^7.1.0 #1323 baseflow.com
  # image_gallery_saver: ^1.6.9 #191 unknown
  # fluttertoast: ^8.0.6 #1057 karthikonnam.dev
  horizontal_data_table: ^4.1.5 #146 unknown
  scrollable_positioned_list: ^0.3.5 #715 google.dev
  # english_words: ^4.0.0 #221 unknown
  pdf: ^3.4.2 #799 nfet.net
  # advance_pdf_viewer: ^2.0.0 #186 dlohani.com.np
  native_pdf_view: ^6.0.0+1 #253 serge.software
  printing: ^5.6.3 #575 nfet.net
  pluto_grid: ^5.4.9 #389 weblaze.dev

  # flutter_sound: ^8.1.1 #446 dooboolab.com
  # audioplayers: ^0.19.0 #880 fireslime.xyz

  form_field_validator: ^1.1.0 #153 unknown
  dropdown_search: ^5.0.6 #553 salimdev.ovh
  # searchable_dropdown: ^1.1.3 #248 unknown
  # fl_chart: ^0.36.3 #1795 ikhoshabi.com
  # cached_network_image: ^3.0.0
  # expandable: ^5.0.1 #698 MIT
  # dio: ^4.0.0 #2595 flutterchina.club
  # ndialog: ^4.1.0 #80 nizwar.id
  google_fonts: ^4.0.3
  charts_flutter: ^0.12.0
  get: ^4.6.0
  data_table_2: ^2.0.3
  substring_highlight: ^1.0.33
  # selectable_autolink_text: ^2.3.0
  quiver: ^3.0.1 #340 google.dev
  rsa_encrypt: ^2.0.0 #43 unverified - scared not compatible later
  number_display: ^3.0.0
  image: ^3.1.0
  hand_signature: ^3.0.1
  flutter_tesseract_ocr: ^0.4.20 
  extended_masked_text: ^2.3.1
  # unorm_dart: ^0.2.0
  # normalizer: ^0.0.2+3
  # string_validator: ^0.3.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/tessdata/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
